### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by thanhphamtroll1999** [ThanhTrungGVC/INT2208-7-2019#26]
-Là một người mua hàng, tôi muốn các mẫu hàng được cập nhật liên tục thuận tiện cho việc tìm hiểu và đưa ra quyết định mua hàng.
-Là một người mua hàng, tôi muốn nhận được thông báo về những ưu đãi khi cửa hàng có chương trình khuyến mãi.
-Là một khách hàng, tôi muốn thông tin của mình được giữ kín, cửa hàng sẽ chịu trách nhiệm  khi thông tin của tôi bị lộ ra.
-Là một quản trị viên, tôi muốn được xem mọi nội dung về khách hàng, đơn hàng.

**Comment by VuThanhThien** [comment]
-Là một khách hàng, tôi muốn giao diện của ứng dụng đẹp mắt, nhẹ nhàng.

**Comment by VuThanhThien** [comment]
-Là một khách hàng, tôi muốn giao diện đăng nhập đơn giản, dễ nhìn.
